include: package:extra_pedantic/analysis_options.1.2.0_flutter.yaml

analyzer:
  exclude:
    # workaround for https://github.com/dart-lang/sdk/issues/42910
    - 'example/**'

linter:
  rules:
    - avoid_types_as_parameter_names
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_field_initializers_in_const_classes
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - camel_case_types
    - camel_case_extensions
    - omit_local_variable_types
    - overridden_fields
    - non_constant_identifier_names
    - prefer_adjacent_string_concatenation
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_single_quotes
    - prefer_interpolation_to_compose_strings
    - sort_constructors_first
    - unnecessary_statements
    - unnecessary_this
    - unnecessary_new
    - unnecessary_lambdas
    - unnecessary_brace_in_string_interps
    - use_key_in_widget_constructors