builders:
  featureBuilder:
    import: "package:d3_sealed/d3_sealed.dart"
    builder_factories: ["featureBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: root_package