name: d3_sealed
description: A Dart 3-style sealed class builder.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.3.1
  build_config: ^1.1.1
  characters: ^1.2.1
  source_gen: ^1.2.7
  sealed_annotations: any
  uuid: ^3.0.7
  collection: ^1.17.0
  diacritic: ^0.1.3
  file: ^6.1.4
  flutter:
    sdk: flutter
  meta: ^1.8.0
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  extra_pedantic: ^3.0.0
